author: StupidBot
version: 1.0.0
name: eAnnouncer
main: com.stupidbot.universalannouncer.Main
description: Announcements!
commands:
  reloadannouncements:
    description: Reloads announcement(s)!
    aliases: [reloadannouncement, reloaduniversalannouncement, reloaduniversalannouncements]
    usage: /<command>
  toggleannouncements:
    description: Hides hides annoucement(s)!
    aliases: [toggleannouncement]
    usage: /<command>
  testannouncements:
    description: Test announcement(s)!
    aliases: [testannouncement]
    usage: /<command> <announcement id>